Repository luanti-org/luanti-org.github.io, pull requests merged in 2019-07, with the labels that each got.

#177 Stable 0.4 -> Stable 5.0
  downloads.html
Labels: @content

#180 Add a fallback color for the background image
  _sass/_home.scss
Labels: @visuals, enhancement

#181 Fix Travis CI setup and HTML errors reported by HTMLProofer
  .travis.yml
  404.html
  _config.yml
  _includes/footer.html
  _includes/header.html
  credits.html
  customize.html
  index.html
  servers.html
Labels: bug

#176 Improve Get Involved layout
  _data/community.yml
  _includes/footer.html
  _sass/_base.scss
  get-involved.html
  media/logos/forum.svg
  media/logos/github.png
  media/logos/irc.svg
  media/logos/reddit.png
  media/logos/servers.svg
  media/logos/wiki.svg
Labels: enhancement
